### PR TITLE
Add "Frontend Dependencies" section in Dev Docs

### PR DESCRIPTION
**Pull request by michelesr**

### CODE REVIEW

**Comment by kobe25** [comment]
Great job!

**Comment by kobe25** [comment]
Since the behaviour is the same, can you add some notes about the backend dependencies?

**Comment by feroda** [comment]
Great job +1! However I think that there i no need to make dbtest and dbdump in the frontend.

I agree with @kobe25 if you have clear in mind where backend requirements are kept, you should open a section ### Backend dependencies specifying the files to modify and the rebuild command. (Maybe also the backend rebuilding does not need dbtest, dbdump redo since it is kept in the db container image am I right?)

**Comment by michelesr** [comment]
>Great job +1! However I think that there i no need to make dbtest and dbdump in the frontend.

After an update of the `front` image, all the application containers have to be recreated to provide correct linking between them (the linking is made at container start, and if `front` change IP the other container will still resolve its name with the old IP, so recreation of them is inevitable).

If the `db` container is recreated, the data needs to be reloaded, so `make dbtest` is necessary (as well as `make dbdump` when dumping is wanted).

**Comment by kobe25** [comment]
Enhancement proposal:  moving all these commands directly into the `Makefile` and making them available via `make rebuild-back` and `make rebuild-front`

**Pull request merged**
