### PR TITLE
LEGACY appears, code cleaning, Dockerfile for backend updated

### PR DESCRIPTION
**Pull request by feroda**

### CODE REVIEW

**Comment by warp10** [comment]
Why did you remove apt in favor of apt-get? That's quite anti-historic

**Comment by feroda** [comment]
I did it because when the image is built I get some warnings about the non-interactive use of `apt` . Weird red docker warnings make me afraid...

It doesn't really matter to me which frontend use to the dpkg, tell me and I change it.

**Comment by warp10** [comment]
Weird it doesn't show the same warnings with apt-get. In any case, better to keep up with apt, which is the bright future of dpkg frontends.

**Comment by michelesr** [comment]
The warnings are related to the fact that apt hasn't a stable cli yet, and should be used with caution in scripts.

But for simple commands (like `apt install -y ...`) this shouldn't be an issue

**Pull request merged**
